[build]
  # Build from the root directory (files were moved from mealmind subdirectory)
  base = "."
  publish = "dist"
  command = "npm run build"

# Secrets scanning configuration
[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning for known safe files that contain examples
  SECRETS_SCAN_OMIT_PATHS = ".env.local,.env.example,README.md,mealmind/README.md"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
